name: Ping MySQL Databases

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  ping-databases:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install MySQL client
      run: sudo apt-get update && sudo apt-get install -y mysql-client

    - name: Ping MySQL Databases
      run: |
        i=1
        while IFS= read -r db_url; do
          if mysql --connect-timeout=5 --ssl-mode=REQUIRED "$db_url" -e "SELECT 1;" >/dev/null 2>&1; then
            echo "Database no-$i successfully pinged"
          else
            echo "Database no-$i can't be reached"
          fi
          ((i++))
        done < databases.txt
