name: Ping MySQL Databases

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  ping-databases:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install MySQL client
      run: sudo apt-get update && sudo apt-get install -y mysql-client

    - name: Ping MySQL Databases
      run: |
        i=1
        DB_URLS=$(cat databases.txt)
        for DB_URL in $DB_URLS; do
          USER=$(echo "$DB_URL" | sed -E 's|^mysql://([^:]+):([^@]+)@.*$|\1|')
          PASSWORD=$(echo "$DB_URL" | sed -E 's|^mysql://[^:]+:([^@]+)@.*$|\1|')
          HOST=$(echo "$DB_URL" | sed -E 's|^mysql://[^@]+@([^:]+):.*$|\1|')
          PORT=$(echo "$DB_URL" | sed -E 's|^mysql://[^@]+@[^:]+:([^/]+)/.*$|\1|')
          DATABASE=$(echo "$DB_URL" | sed -E 's|^mysql://[^@]+@[^:]+:[^/]+/(.*)\?.*$|\1|')
          if mysql -u "$USER" -p"$PASSWORD" -h "$HOST" -P "$PORT" -D "$DATABASE" -e "SELECT 1;"; then
            echo "Database no-$i successfully pinged"
          else
            echo "Database no-$i can't be reached"
          fi
          ((i++))
        done
